# Generated by Django 4.1.7 on 2023-04-01 14:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('entrega_3', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Libro',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre_libro', models.CharField(max_length=100)),
                ('genero', models.TextField(max_length=100)),
                ('cantidad_paginas', models.TextField(max_length=2000)),
            ],
        ),
        migrations.AlterField(
            model_name='animal',
            name='nombre_animal',
            field=models.CharField(max_length=100),
        ),
    ]
